version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - name: Install global dev env
        run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}  
      - name: Bootstrap lerna throughout the packages
        run: node_modules/.bin/lerna bootstrap
      - name: Build all packages
        run: yarn build
      - name: Trigger the test suite over all the packages
        run: yarn test
